import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";

const inter = Orbitron({
  weight: "900",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Levelling App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
